repos:
  kinetic-backports:
    main_ref: "master"
    build_args:
      ALPINE_VERSION: "3.7"
      ROS_DISTRO: "kinetic"
    envs:
      JOBS: 4
      PURGE_OBSOLETE: "yes"
    args: ["backports"]
    repo_path: "/home/builder/packages/backports"
    sign_key_path: "/home/builder/.abuild/builder@alpine-ros-experimental.rsa"
    upload:
      - remote: "main"
        paths: ["v3.7/backports"]
        archive_paths: ["archives/v3.7/backports"]
      - remote: "mirror"
        paths: ["v3.7/backports"]
  kinetic:
    main_ref: "master"
    build_args:
      ALPINE_VERSION: "3.7"
      ROS_DISTRO: "kinetic"
    envs:
      JOBS: 4
      PURGE_OBSOLETE: "yes"
    args: ["ros/kinetic"]
    repo_path: "/home/builder/packages/ros/kinetic"
    sign_key_path: "/home/builder/.abuild/builder@alpine-ros-experimental.rsa"
    upload:
      - remote: "main"
        paths: ["v3.7/ros/kinetic"]
        archive_paths: ["archives/v3.7/ros/kinetic"]
      - remote: "mirror"
        paths: ["v3.7/ros/kinetic"]
  melodic-backports:
    main_ref: "master"
    build_args:
      ALPINE_VERSION: "3.8"
      ROS_DISTRO: "melodic"
    envs:
      JOBS: 4
      PURGE_OBSOLETE: "yes"
    args: ["backports"]
    repo_path: "/home/builder/packages/backports"
    sign_key_path: "/home/builder/.abuild/builder@alpine-ros-experimental.rsa"
    upload:
      - remote: "main"
        paths: ["v3.8/backports"]
        archive_paths: ["archives/v3.8/backports"]
      - remote: "mirror"
        paths: ["v3.8/backports"]
  melodic:
    main_ref: "master"
    build_args:
      ALPINE_VERSION: "3.8"
      ROS_DISTRO: "melodic"
    envs:
      JOBS: 4
      PURGE_OBSOLETE: "yes"
    args: ["ros/melodic"]
    repo_path: "/home/builder/packages/ros/melodic"
    sign_key_path: "/home/builder/.abuild/builder@alpine-ros-experimental.rsa"
    upload:
      - remote: "main"
        paths: ["v3.8/ros/noetic"]
        archive_paths: ["archives/v3.8/ros/noetic"]
      - remote: "mirror"
        paths: ["v3.8/ros/noetic"]
  noetic:
    main_ref: "master"
    build_args:
      ALPINE_VERSION: "3.11"
      ROS_DISTRO: "noetic"
    envs:
      JOBS: 4
      PURGE_OBSOLETE: "yes"
    args: ["ros/noetic"]
    repo_path: "/home/builder/packages/ros/noetic"
    sign_key_path: "/home/builder/.abuild/builder@alpine-ros-experimental.rsa"
    upload:
      - remote: "main"
        paths: ["v3.11/ros/noetic"]
        archive_paths: ["archives/v3.11/ros/noetic"]
      - remote: "mirror"
        paths: ["v3.11/ros/noetic"]
  noetic-backports:
    main_ref: "master"
    build_args:
      ALPINE_VERSION: "3.11"
      ROS_DISTRO: "noetic"
    envs:
      JOBS: 4
      PURGE_OBSOLETE: "yes"
    args: ["backports"]
    repo_path: "/home/builder/packages/backports"
    sign_key_path: "/home/builder/.abuild/builder@alpine-ros-experimental.rsa"
    upload:
      - remote: "main"
        paths: ["v3.11/backports"]
        archive_paths: ["archives/v3.11/backports"]
      - remote: "mirror"
        paths: ["v3.11/backports"]
